mynewapp/urls.py
from django.urls import path
from .import views 


app_name='mynewapp'
urlpatterns = [
	path('', views.index, name='index'),
    path('user_reg/', views.user_reg, name='user_reg'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_home/<int:id>/', views.user_home, name='user_home'),
    path('show/<int:id>/', views.show, name='show'),
    # path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:id>', views.destroy, name='destroy'),
    path('changepassword/<int:id>/',views.changepassword, name='changepassword'),
    path('logout/', views.logout, name='logout'),
    path('image/', views.image, name='image'),
    path('imageshow/', views.imageshow, name='imageshow'),
    path('about/<int:pk>/', views.about, name='about'),
    # path(r'^.*/$', views.View_404, name='View_404')
    
    
    

  
    ]

mynewproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mynewapp.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mynewapp/models.py
from django.db import models
# from django.core.validators import RegexValidator




gender = (
	('male', 'Male'),
	('female','Female'),
	('transgender','Transgender')
	)
maritialstatus = (
	('married', 'Married'),
	('unmarried','Unmarried')
	)
edu = (
	('sslc','Sslc'),
	('plus2','Plus2'),
	('degree','Degree'),
	('pg','Pg'),
	('others','Others'),
	)
	
languageknown = (
	('malayalam', 'Malayalam'),
	('english', 'English'),
	('hindi', 'Hindi')
	)

district = (
    ('kasaragod','Kasaragod'),
    ('kannur','Kannur'),
    ('kozhikkode','Kozhikkode'),
    ('vayanad','Vayanad'),
    ('malappuram','Malappuram'),
    ('thrissure','Thrissure'),
    ('idukki','Idukki'),
    ('palakkad','Palakkad'),
    ('ernakulam','Ernakulam'),
    ('alappuzha','Alappuzha'),
    ('pathanamthitta','Pathanamthitta'),
    ('kottayam','Kottayam'),
    ('kollam','Kollam'),
    ('thiruvananthapuram','Thiruvananthapuram'),
    )	


	
	

	
class User(models.Model):
	Name = models.CharField(max_length=100)
	Address = models.CharField(max_length=100)
	Gender = models.CharField(max_length=100,default='')
	Email = models.EmailField()
	Maritialstatus = models.CharField(max_length=100,default='')
	Educationalqualification = models.CharField(max_length=100,default='')
	Languageknown = models.CharField(max_length=100,choices=languageknown)
	District = models.CharField(max_length=100,choices=district)
	Password = models.CharField(max_length=8)
	Confirmpassword = models.CharField(max_length=8)
	Photo = models.ImageField(upload_to='media/')
	Status = models.BooleanField(default=False)
	def __str__(self):
		return self.Name


class img(models.Model):
	Name = models.CharField(max_length=100)
	Price = models.CharField(max_length=100)
	Location = models.CharField(max_length=100)
	Colour = models.CharField(max_length=100)
	Photo = models.ImageField(upload_to='media/')

	def __str__(self):
		return self.Name

mynewapp/forms.py
from django import forms
from .models import User
from. models import img
gender = (
	('Male', 'Male'),
	('Female','Female'),
	('Transgender','Transgender')
	)
maritialstatus = (
	('Married', 'Married'),
	('Unmarried','Unmarried')
	)
edu= [
    ('Sslc', 'Sslc'),('Plus2', 'Plus2'),('Degree', 'Degree'),('Pg', 'Pg'),('Others', 'Others')
    ]
# district = (
#     ('kasaragod','Kasaragod'),
#     ('kannur','Kannur'),
#     ('kozhikkode','Kozhikkode'),
#     ('vayanad','Vayanad'),
#     ('malappuram','Malappuram'),
#     ('thrissure','Thrissure'),
#     ('idukki','Idukki'),
#     ('palakkad','Palakkad'),
#     ('ernakulam','Ernakulam'),
#     ('alappuzha','Alappuzha'),
#     ('pathanamthitta','Pathanamthitta'),
#     ('kottayam','Kottayam'),
#     ('kollam','Kollam'),
#     ('thiruvananthapuram','Thiruvananthapuram'),
#     )


class UserRegForm(forms.ModelForm):

    Password=forms.CharField(widget=forms.PasswordInput,min_length=8,max_length=8)
    Confirmpassword=forms.CharField(widget=forms.PasswordInput,min_length=8,max_length=8)
    Gender=forms.CharField(label='Gender', widget=forms.RadioSelect(choices=gender))
    Educationalqualification=forms.MultipleChoiceField(choices=edu,widget=forms.CheckboxSelectMultiple(attrs={'class':'qual'}))
    Maritialstatus=forms.CharField(label='Maritialstatus',widget=forms.RadioSelect(choices=maritialstatus))
    # District=forms.CharField(label='District',widget=forms.RadioSelect(choices=district))
    class Meta():
        model = User
        fields = ('Name','Address','Gender','Maritialstatus','Educationalqualification','Languageknown','District','Email','Password','Confirmpassword','Photo')

class UserLoginForm(forms.ModelForm):
    Password= forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('Email', 'Password')
class UserUpdateForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ('Name','Address','Gender','Maritialstatus','Educationalqualification','Languageknown','District','Email','Photo')


class PasswordChangeForm(forms.ModelForm):
    Oldpassword=forms.CharField(widget=forms.PasswordInput,min_length=8,max_length=16)
    Newpassword=forms.CharField(widget=forms.PasswordInput,min_length=8,max_length=16)
    Confirmpassword=forms.CharField(widget=forms.PasswordInput,min_length=8,max_length=16)

    class Meta():
        model = User
        fields = ('Oldpassword','Newpassword','Confirmpassword')




class ImageForm(forms.ModelForm):

    class Meta():
        model= img
        fields=('Name','Price','Location','Colour','Photo')

class ImageshowForm(forms.ModelForm):
    class Meta():
        model=img
        fields=('Photo',)

class AboutForm(forms.ModelForm):
    class Meta():
        model=img 
        fields=('Name','Price','Location','Colour','Photo')      
 
         

mynewapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . forms import UserRegForm,UserLoginForm,UserUpdateForm,PasswordChangeForm,ImageForm,ImageshowForm,AboutForm
from . models import User
from . models import img
from django.contrib.auth import logout
from django.contrib import messages, auth
from django.views.decorators.csrf import csrf_exempt

def index(request):
    return render(request, 'index.html')

def image(request):
    if request.method =='POST':
        form =ImageForm(request.POST,request.FILES)
        if form.is_valid():
            name = form.cleaned_data['Name']
            price =form.cleaned_data['Price']
            location =form.cleaned_data['Location']
            colour = form.cleaned_data['Colour']
            photo = form.cleaned_data['Photo']
            form.save()

            return redirect("/imageshow")
            return render(request,'image.html',{'form':form})
    else:
        form=ImageForm()
    return render(request,'image.html',{'form':form})

def imageshow(request):
    Img=img.objects.all()
    return render(request,'imageshow.html',{'Img':Img})



    



def user_reg(request):
    if request.method == 'POST':
        form = UserRegForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data['Name']
            address = form.cleaned_data['Address']
            photo = form.cleaned_data['Photo']
            gender = form.cleaned_data['Gender']
            maritialstatus = form.cleaned_data['Maritialstatus']
            educationalqualification = form.cleaned_data['Educationalqualification']
            languageknown = form.cleaned_data['Languageknown']
            district = form.cleaned_data['District']
            email = form.cleaned_data['Email']
            password = form.cleaned_data['Password']
            confirmpassword = form.cleaned_data['Confirmpassword']
            
            ur = User.objects.filter(Email=email).exists()

            if ur:
                msg="User with same email is already exist!"
                args={'form':form,'error':msg}
                return render(request,'user_reg.html',args)

            elif password!=confirmpassword:
                msg="Enter correct password! passwword mismatch"
                args={'form':form,'error':msg}
                return render(request,'user_reg.html',args)

            else:
                res=User(Name=name,Address=address,Gender=gender,Maritialstatus=maritialstatus,Educationalqualification=educationalqualification,Languageknown=languageknown,District=district,Email=email,
                            Password=password,Confirmpassword=confirmpassword,Photo=photo)
                res.save()
                return redirect('/user_reg')
    else:
        form=UserRegForm()
    return render(request,'user_reg.html',{'form':form})


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['Email']
            password = form.cleaned_data['Password']

            try:
                ur = User.objects.get(Email=email, Status=True)

                if not ur:
                    msg="Incorrect Email or password!"
                    args={'form':form,'error':msg}
                    return render(request,'user_login.html',args)

                elif password!=ur.Password:
                    msg="Incorrect Email or Password"
                    args={'form':form,'error':msg}
                    return render(request,'user_login.html',args)

                else:
                    request.session['email'] = email
                    request.session['sid'] = ur.id
                    return redirect('/user_home/%s' % ur.id)
            except:
                msg = "Incorrect Email or password!"
                args = {'form': form,'error': msg}
                return render(request, 'user_login.html',args)
    else:
        form=UserLoginForm()
    return render(request,'user_login.html',{'form':form})
# def edit(request,pk):
#     user=User.objects.get(id=pk)
#     form=UserEditForm(request.POST,instance=user)
#     if form.is_valid():
#         form.save()
#         return redirect("/show")
#     return render(request,'/edit.html',{'user':users})
def show(request, id):
    users=User.objects.get(id=id)
    form=UserUpdateForm(request.POST,instance=users)
    if form.is_valid():
        form.save()
        return redirect("/user_home")
    return render(request,'show.html',{'users':users})



def about(request,pk):
    Img=img.objects.get(id=pk)
    return render(request,'about.html',{'Img':Img})

def user_home(request,id):
    if request.session.has_key:
        email = request.session['email']
        uid = request.session['sid']
        user = User.objects.get(id=id)
        ur = User.objects.get(Email=email) 
        return render(request, 'user_home.html', {'ur':ur, 'user':user})


def destroy(request, id):
    user = User.objects.get(id=id)
    user.delete()
    return redirect("/")

def changepassword(request,id):
    uid=request.session['sid']
    user=User.objects.get(id=id)
    if request.method=='POST':
        form=PasswordChangeForm(request.POST)
        if form.is_valid():
            oldpassword = form.cleaned_data['Oldpassword']
            newpassword = form.cleaned_data['Newpassword']
            confirmpassword = form.cleaned_data['Confirmpassword']
            if oldpassword!=user.Password:
                msg="Enter correctpassword"
                return render(request,'changepassword.html',{'form':form,'error':msg,'user':user})
            elif newpassword!=confirmpassword:
                msg="Password does not match"
                return render(request,'changepassword.html',{'form':form,'error':msg,'user':user})
            else:
                user.Password =newpassword
                user.Confirmpassword = confirmpassword
                user.save()
                msg ="Password Change Successfully"
                return redirect('/user_home/%s'%id)
                return render(request,'changepassword.html',{'form':form,'error':msg,'user':user})
    else:
        form=PasswordChangeForm()
        return render(request,'changepassword.html',{'form':form,'user':user})
       


    

    
    

def logout(request):
    # logout(request)
    messages.info(request,'loggedout successfully')
    return redirect('/')



# def View_404(request):
#     Img=img.objects.all()
#     return redirect("/")
    

mynewapp/templates/about.html
{% extends "base.html" %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
	
</head>

<body>
	{% block content %}
		<form action="{% url 'mynewapp:about' Img.id %}" method='post' enctype="multipart/form-data" >
		{% csrf_token %}
		
		<table>
				{% if Img %}
			
				<tr>
					<td>
						<h2 style="text _align:center;">About</h2>
					</td>
				</tr>
				<tr>
					<td>Name:</td>
					<td><input type="text" name="Name" value="{{Img.Name}}">
					</td>
				</tr>
				<tr>
					<td>Price:</td>
					<td><input type="text" name="Price" value="{{Img.Price}}">
					</td>
				</tr>
				<tr>
					<td>Location:</td>
					<td><input type="text" name="Location" value="{{Img.Location}}">
					</td>
				</tr>
				<tr>
					<td>Colour:</td>
					<td><input type="text" name="Colour" value="{{Img.Colour}}">
					</td>
				</tr>
				
				<tr>
					<td>Photo:</td>
					<td><img src ="{{Img.Photo.url}}" style="width:60px;height:60px"></td>
				</tr>
				{% endif %}
			</form>
		</table>
	</form>
	{% endblock %}
</body>
</html>
			

mynewapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>mind</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- fevicon -->
  <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
  <!-- bootstrap css -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'css/responsive.css' %}">  
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="{% static 'https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %}">
  <link rel="stylesheet" href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css' %}" media="screen">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout">
  <!-- loader  -->
  <div class="{% static 'loader_bg' %}">
    <div class="loader"><img src="{% static 'images/loading.gif' %}" alt="#" /></div>
  </div>
  <!-- end loader -->
  <!-- header -->
  <header>
    <!-- header inner -->
    <div class="header-top">
      <div class="header">
        <div class="container-fluid">
          <div class="row">
            <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
              <div class="full">
                <div class="center-desk">
                  <div class="logo">
                    <a href="index.html"><img src="{% static 'images/logo.png' %}" alt="#" /></a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">
              <div class="header_information">
               <div class="menu-area">
                <div class="limit-box">
                  <nav class="main-menu ">
                    <ul class="menu-area-main">
                      <li class="active"> <a href=""></a> </li>
                      <li> <a href="{% url 'mynewapp:user_reg' %}"> Register</a> </li>
                      <li> <a href="{% url 'mynewapp:user_login' %}">Login</a> </li>
                      <li> <a href="{% url 'mynewapp:image' %}">uploadimage</a> </li>
                      <li> <a href="{% url 'mynewapp:logout' %}">Logout</a></li>
                      <li> <a href="#contact">Contact</a> </li>
                     </ul>
                   </nav>
                 </div>
               </div> 
               <div class="mean-last">
                       <a href="#"><img src="{% static 'images/search_icon.png' %}" alt="#" /></a> <a href="#">login/sing up</a></div>              
             </div>
           </div>
         </div>
       </div>
     </div>
     <!-- end header inner -->

     <!-- end header -->
     <section class="slider_section">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">

            <div class="container-fluid padding_dd">
              <div class="carousel-caption">
                <div class="row">
                  <div class="col-xl-5 col-lg-5 col-md-5 col-sm-12">
                    <div class="text-bg">
                      <h1>Search your Favorite Course here</h1>
                      <p>TOP NOTCH COURSES FROM TRAINED PROFESSIONALS</p>
                      <a href="#">Read more</a> <a href="#">get a qoute</a>
                    </div>
                  </div>
                  <div class="col-xl-7 col-lg-7 col-md-7 col-sm-12">
                    <div class="images_box">
                      <figure><img src="{% static 'images/img2.png' %}"></figure>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">

            <div class="container-fluid padding_dd">
              <div class="carousel-caption">

                <div class="row">
                  <div class="col-xl-5 col-lg-5 col-md-5 col-sm-12">
                    <div class="text-bg">
                      <h1>Search your Favorite Course here</h1>
                      <p>TOP NOTCH COURSES FROM TRAINED PROFESSIONALS</p>
                      <a href="#">Read more</a><a href="#">get a qoute</a>
                    </div>
                  </div>

                  <div class="col-xl-7 col-lg-7 col-md-7 col-sm-12">
                    <div class="images_box">
                      <figure><img src="{% static 'images/img2.png' %}"></figure>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>


          <div class="carousel-item">

            <div class="container-fluid padding_dd">
              <div class="carousel-caption ">
                <div class="row">
                  <div class="col-xl-5 col-lg-5 col-md-5 col-sm-12">
                    <div class="text-bg">
                      <h1>Search your Favorite Course here</h1>
                      <p>TOP NOTCH COURSES FROM TRAINED PROFESSIONALS</p>
                      <a href="#">Read more</a> <a href="#">get a qoute</a>
                    </div>
                  </div>
                  <div class="col-xl-7 col-lg-7 col-md-7 col-sm-12">
                    <div class="images_box">
                      <figure><img src="{% static 'images/img2.png' %}"></figure>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

</section>
</div>
</header>



<!-- about  -->

          
<!-- end abouts -->



<!-- our -->




<!-- end our -->
<!-- Courses -->

          
          
<!-- end Courses -->

<!-- learn -->
<!-- end MAKE --> 
<!-- end learn --> 


<!-- contact -->

              

    <!-- end contact -->
  {% block content %}
{% endblock %}

    <!--  footer -->
    <footr>
      <div class="footer ">
        <div class="container">
          <div class="row">

            <div class="col-md-12">
              <form class="news">
                <input class="newslatter" placeholder="Email" type="text" name=" Email">
                <button class="submit">Subscribe</button>
              </form>
            </div>
            <div class="col-md-12">
              <h2>Newsletter</h2>
              <span>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in  </span>
            </div>
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 ">
              <div class="row">
                <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 ">
                  <div class="address">
                    <h3>Contact us </h3>
                    <ul class="loca">
                      <li>
                        <a href="#"><img src="{% static 'icon/loc.png' %}" alt="#" /></a>London 145
                        <br>United Kingdom </li>
                        <li>
                          <a href="#"><img src="{% static 'icon/email.png' %}" alt="#" /></a>demo@gmail.com </li>
                          <li>
                            <a href="#"><img src="{% static 'icon/call.png' %}" alt="#" /></a>+12586954775 </li>
                          </ul>
                          <ul class="social_link">
                            <li><a href="#"><img src="{% static 'icon/fb.png' %}"></a></li>
                            <li><a href="#"><img src="{% static 'icon/tw.png' %}"></a></li>
                            <li><a href="#"><img src="{% static 'icon/lin(2).png' %}"></a></li>
                            <li><a href="#"><img src="{% static 'icon/instagram.png' %}"></a></li>
                          </ul>

                        </div>
                      </div>
                      <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="address">
                          <h3>Courses</h3>
                          <ul class="Menu_footer">
                            <li class="active"> <a href="#">Masters Degree</a> </li>
                            <li><a href="#">Post GraduateU</a> </li>
                            <li><a href="#">Ndergraduate</a> </li>
                            <li><a href="#">Engineering</a> </li>
                            <li><a href="#">Ph.D Degree</a> </li>
                          </ul>
                        </div>
                      </div>
                      <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="address">
                          <h3>Information</h3>
                          <ul class="Links_footer">
                            <li class="active"><a href="#">Campus Tour</a> </li>
                            <li><a href="#">Student Lifes</a> </li>
                            <li><a href="#">Cholarship</a> </li>
                            <li><a href="#"> Admission</a> </li>
                            <li><a href="#">Leadership</a> </li>
                          </ul>
                        </div>
                      </div>

                      <div class="col-lg-3 col-md-6 col-sm-6 ">
                        <div class="address">
                          <a href="index.html"> <img src="{% static 'images/logo1.jpg' %}" alt="logo"></a>
                        </div>
                      </div>
                    </div>
                  </div>

                </div>

              </div>
              <div class="copyright">
                <div class="container">
                  <p>Copyright © 2019 Design by <a href="https://html.design/">Free Html Templates </a></p>
                </div>
              </div>
            </div>
          </footr>
          <!-- end footer -->
          <!-- Javascript files-->
          <script src="{% static 'js/jquery.min.js' %}"></script>
          <script src="{% static 'js/popper.min.js' %}"></script>
          <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
          <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
          <script src="{% static 'js/plugin.js'}"></script>
          <!-- sidebar -->
          <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
          <script src="{% static 'js/custom.js' %}"></script>
          <script src="{% static 'https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js' %}"></script>


          <script>
// This example adds a marker to indicate the position of Bondi Beach in Sydney,
// Australia.
function initMap() {
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 11,
    center: {
      lat: 40.645037,
      lng: -73.880224
    },
  });

  var image = 'images/maps-and-flags.png';
  var beachMarker = new google.maps.Marker({
    position: {
      lat: 40.645037,
      lng: -73.880224
    },
    map: map,
    icon: image
  });
}
</script>
<!-- google map js -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>
<!-- end google map js -->



</body>

</html>

mynewapp/templates/imageshow.html
{% extends "base.html" %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>my page</title>
</head>
<body>
	{% block content %}

		<form action="{% url 'mynewapp:imageshow' %}" method='post' enctype="multipart/form-data" >
			{% csrf_token %}
			{% for x in Img %}
			
				<tr>
					<td>
						<a href="{% url 'mynewapp:about' x.id %}">
							<img src="{{x.Photo.url}}" width="500px"/>
						</a>
					</td>
				</tr>
					
				
			{% endfor %}
				<div>
    		</div>
    	</form>
    {% endblock %}
</body>
</html>
    		

  <!--       <div>
        <tr> 
        	<td>success</td>
        </tr>
    </div>

				

		
		
		
	

	

	
	

mynewapp/templates/logout.html
<html>
<head>
	<title></title>
</head>
<body>
	{% block content %}
	<div>
		<!-- <form action="{% url 'mynewapp:logout' %}" method='POST' enctype="multipart/form-data"> -->
		<!-- <form methord="POST" action="{% url 'mynewapp:index' %}"> -->
	<!-- <div class = "content"> -->
			<!-- <div class ="section-inner clearfix"> -->
		<!-- <p> you have been logged out click <a href="{% url 'mynewapp:user_login' %}">here</a> to login again</p> -->
		<a href="{% url 'django.contrib.auth.views.logout' %}next=/">logout
		</a>
			</div>
		}
	</div>
	{% endblock %}
</body>
</html>

mynewapp/templates/user_home.html
{% extends "base.html" %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	{% block content %}
		<form action="{% url 'mynewapp:user_home' user.id %}" method=post enctype="multipart/form-data">
			{% csrf_token %}
			{% if user %}
				<img src="{{ user.Photo.url }}" style="width:250px;height:250px">
				
				<a href="/delete/{{ user.id }}">Delete</a>

			{% endif %}

	</form>
	


		<div>
			<tr>
				<td>Success</td>
			</tr>
			<tr>
				<td><a href="{% url 'mynewapp:show' user.id %}">show</a>
				</td>
			</tr>
			<tr>
				<td><a href="{% url 'mynewapp:changepassword' user.id %}">changepassword</a>
				</td>
			</tr>
			<tr>
				<td><a href="{% url 'mynewapp:image' %}">image</a>
				</td>
			</tr>



		</div>


	</form>
{% endblock %}
</body>
</html>